Update distillation_chat_completion.ipynb
latest api requires version, provided v1 as starting point

    351 if not version:
    352     msg = "Must provide either version or label"
--> 353     raise ValidationException(
    354         message=msg,
    355         target=ErrorTarget.MODEL,
    356         no_personal_data_message=msg,
    357         error_category=ErrorCategory.USER_ERROR,
    358         error_type=ValidationErrorType.MISSING_FIELD,
    359     )
    360 # TODO: We should consider adding an exception trigger for internal_model=None
    361 model_version_resource = self._get(name, version)

ValidationException: Must provide either version or label